### ISSUE TITLE
harmonie name

### ISSUE THREAD

**Issue by dekelcohen** [harmonie/test#1]
Hi,

I'm Dekel from http://harmon.ie company. We would like to open a github organization by that name.
Are you working for harmon.ie ? 
If not, would you consider deleting this user name, thus allowing us to open the org ?

**Comment by harmonie** [comment]
Hi,
I'm Harmonie. As stated by [Github's Name Squatting Policy](https://help.github.com/articles/name-squatting-policy/)  account names are provided on a first-come, first-served basis.

Closing this issue as it's not even related to this repository.
